version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'exampleuser'
      POSTGRES_PASSWORD: 'examplepass'
      POSTGRES_DB: 'oopshop'
    ports:
      - '5432:5432'